Repository retest/recheck.cli, pull requests merged in 2020-03, with the labels that each got.

#218 Fix/update recheck
  pom.xml
  src/test/java/de/retest/recheck/cli/subcommands/DiffIT.java
  src/test/java/de/retest/recheck/cli/subcommands/ShowIT.java
Labels: cla-signed

#219 Add custom color scheme to Account
  src/main/java/de/retest/recheck/cli/RecheckCli.java
  src/main/java/de/retest/recheck/cli/subcommands/Account.java
  src/main/java/de/retest/recheck/cli/utils/HelpColorScheme.java
Labels: cla-signed

#220 Update README.md to include Account cmd
  README.md
Labels: cla-signed

#221 Bump recheck version to 1.10.0
  pom.xml
Labels: cla-signed

#222 Finalize changelog for release
  CHANGELOG.md
Labels: cla-signed

#223 Release/v1.10.0
  CHANGELOG.md
  pom.xml
  src/test/java/de/retest/recheck/cli/subcommands/DiffIT.java
  src/test/java/de/retest/recheck/cli/subcommands/IgnoreIT.java
  src/test/java/de/retest/recheck/cli/subcommands/ShowIT.java
  src/test/java/de/retest/recheck/cli/utils/SystemInUtilTest.java
Labels: cla-signed

#224 Fix missing coverage for SonarCloud
  ci/script.sh
  pom.xml
Labels: cla-signed

#225 Synchronize mergify with retest/recheck
  .mergify.yml
Labels: cla-signed

#226 Bump recheck version to 1.10.1-beta.1
  pom.xml
Labels: cla-signed, dependencies

#228 Add dependabot config to ignore recheck dependency
  .dependabot/config.yml
Labels: cla-signed, enhancement

#229 Bump recheck version to 1.10.1
  pom.xml
Labels: cla-signed, dependencies

#230 Remove new line before error message
  src/main/java/de/retest/recheck/cli/utils/ErrorHandler.java
Labels: cla-signed

#231 Prepare changelog for release 1.10.1
  CHANGELOG.md
Labels: cla-signed

#233 Hotfix/v1.10.1
  CHANGELOG.md
  pom.xml
Labels: cla-signed

#232 Add logger warning in case of invalid filter with --exclude
  src/main/java/de/retest/recheck/cli/subcommands/Show.java
Labels: cla-signed

#234 Inform user of used filter
  CHANGELOG.md
  src/main/java/de/retest/recheck/cli/subcommands/Diff.java
  src/main/java/de/retest/recheck/cli/subcommands/Show.java
  src/main/java/de/retest/recheck/cli/utils/FilterUtil.java
  src/test/java/de/retest/recheck/cli/subcommands/DiffIT.java
  src/test/java/de/retest/recheck/cli/subcommands/ShowIT.java
Labels: cla-signed

#235 Bump recheck version to 1.10.2-beta.1
  pom.xml
Labels: cla-signed, dependencies

#236 Bump recheck version to 1.10.2
  pom.xml
Labels: cla-signed, dependencies

#237 Prepare changelog for release 1.10.2
  CHANGELOG.md
Labels: cla-signed

#238 Hotfix/v1.10.2
  CHANGELOG.md
  pom.xml
Labels: cla-signed

#239 Remove deprecated use for diff command
  CHANGELOG.md
  src/main/java/de/retest/recheck/cli/subcommands/Diff.java
  src/main/java/de/retest/recheck/cli/utils/GoldenMasterUtil.java
  src/test/java/de/retest/recheck/cli/subcommands/DiffIT.java
Labels: cla-signed

#240 Fix logger config
  src/main/resources/logback.xml
Labels: cla-signed

#245 Used filter message should only appear when exclude option is used
  src/main/java/de/retest/recheck/cli/utils/FilterUtil.java
  src/test/java/de/retest/recheck/cli/subcommands/DiffIT.java
  src/test/java/de/retest/recheck/cli/subcommands/ShowIT.java
Labels: cla-signed
